# Generated by Django 2.2.12 on 2023-01-30 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jenis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ket', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_member', models.CharField(max_length=10)),
                ('nama', models.CharField(max_length=100)),
                ('alamat', models.CharField(max_length=120)),
                ('tahun_gabung', models.CharField(max_length=20)),
                ('poin', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kodebrg', models.CharField(max_length=8)),
                ('nama', models.CharField(max_length=100)),
                ('stok', models.IntegerField()),
                ('harga', models.BigIntegerField()),
                ('link_brg', models.CharField(max_length=200)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('jenis_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kelas.Jenis')),
            ],
        ),
    ]
