# Generated by Django 2.2.12 on 2023-02-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kelas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pesanan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_member', models.CharField(max_length=10)),
                ('nama_barang', models.CharField(max_length=100)),
                ('pembeli', models.CharField(max_length=150)),
                ('tgl_pesan', models.CharField(max_length=50)),
            ],
        ),
    ]
